[package]
name = "multiplex"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[build-dependencies]
prost-build = "0.10"

[dev-dependencies]
tracing-log = { version = "0.1", features = ["env_logger"] }

[dependencies]
tokio = { version = "1", features = ["full"] }
clap = { version = "3", features = ["derive"] }
prost = "0.10"
bytes = "1"
tracing = { version = "0.1", features = ["log"] }
